apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: install-scripts
spec:
  template:
    spec:
      containers:
        - name: install-scripts
          image: 923411875752.dkr.ecr.us-east-1.amazonaws.com/install-scripts:latest
          env:
          - name: AWS_REGION
            value: us-east-1
          - name: PROJECT_NAME
            value: "install-scripts"
          - name: USE_EC2_PARAMETERS
            value: "1"
          ports:
            - containerPort: 5000
              $patch: delete
            - name: install-scripts
              containerPort: 80