version: '2'

services:
  install-scirpts:
    build: .
    container_name: "replicated.install-scripts"
    networks:
      - default
      - saas_default
    external_links:
      - replicated.saas.mysql:mysql
    ports:
      - "8090:5000"
    restart: always
    environment:
      - ENVIRONMENT=dev
      - REPLICATED_INSTALL_URL=http://localhost:8090
      - MYSQL_USER=replicated
      - MYSQL_PASS=FeReJcBv
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DB=replicated
    volumes:
      - .:/usr/src/app
    command: [python, main.py]

networks:
  saas_default:
    external: true
